/* File is generated by hsttool utility.
 * Do not edit it.
 */


#include "webfiles.h"

const char *html_test = "\
<!DOCTYPE html>\r\n\
<html>\r\n\
  <head>\r\n\
    <title>Hello</title>\r\n\
  </head>\r\n\
  <body>\r\n\
    <div id=\"main\">\r\n\
\t<p>Hello <!--hst uptime --></p>\r\n\
    </div>\r\n\
  </body>\r\n\
</html>\r\n\
";

const char *css_test = "\
\r\n\
";

const char *js_test = "\
\r\n\
";

